# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'exercise-03' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for exercise-03
  pod 'Auth0', '~> 1.13'
  pod 'JWTDecode', '~> 2.1'

end
