# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'exercise-01' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for exercise-01
  pod 'Auth0', '~> 1.13'
  pod 'JWTDecode', '~> 2.1'
  
end
